package:
  name: grn_analysis_tools
  version: 0.0.5

source:
  git_url: https://github.com/Luminarada80/grn_analysis_tools.git
  git_rev: main

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

channels:
  - conda-forge
  - defaults

requirements:
  host:
    - python >=3.10,<3.13.0
    - pip
    - hatchling
  run:
    - python >=3.10
    - pandas >=2.0.3
    - matplotlib >=3.8.0
    - numpy >=1.24.3
    - scikit-learn

about:
  home: https://github.com/Luminarada80/grn_analysis_tools
  license: MIT
  description: |
    A package with helper functions for analyzing gene regulatory network inference methods
  dev_url: https://github.com/Luminarada80/grn_analysis_tools
  doc_source_url: https://github.com/Luminarada80/grn_analysis_tools/blob/main/README.md

  extra:
    recipe-maintainers:
      - Luminarada80