name: Conda Build and Publish

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Optional: Test on PRs to main branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: base

      # Step 3: Install conda-build
      - name: Install conda-build
        run: conda install -y conda-build

      # Step 4: Verify conda-build
      - name: Verify conda-build
        run: conda-build --version

      # Step 5: Build the Conda Package
      - name: Build Conda Package
        run: conda-build conda-recipe

      # Step 6: Upload the Conda Package
      - name: Upload Conda Package
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda login --token $ANACONDA_API_TOKEN
          anaconda upload /usr/share/miniconda/conda-bld/noarch/*.tar.bz2 --force
          
      - name: Install twine
        run: |
          pip install twine
          - name: Publish to PyPI
          env:
            TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          run: |
            python setup.py sdist bdist_wheel
            twine upload dist/*