name: Conda Build and Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true

    - name: Create and activate build environment
      run: |
        conda create -n build-env -y conda-build anaconda-client
        source activate build-env

    - name: Build the package
      id: build-conda
      run: |
        PACKAGE_PATH=$(conda build conda-recipe --output)
        echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV

    - name: Test the built package
      run: |
        conda create -n test-env -y $PACKAGE_PATH
        conda activate test-env
        python -c "import grn_analysis_tools; print('Package imported successfully!')"

    - name: Upload package to Anaconda.org
      if: github.ref == 'refs/heads/main'
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        anaconda upload $PACKAGE_PATH --force
