name: Conda Build and Publish
on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
  pull_request:
    branches:
      - main  # Optional: Test on PRs to main branch
jobs:
  build-and-publish:
    # GitHub actions uses virual machines to run workflows
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
    # Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        auto-activate-base: true
    # Install dependencies for conda-build
    - name: Install conda-build and anaconda-client
      run: |
        conda install -y conda-build anaconda-client
    # Build the Conda package
    - name: Build the package
      run: |
        conda run -n base conda-build conda-recipe
    # Upload to Anaconda.org (Optional)
    - name: Upload package to Anaconda.org
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
      run: |
        anaconda upload ~/conda-bld/**/grn_analysis_tools-*.tar.bz2
    
    - name: Install twine
      run: |
        pip install twine
        - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*